version: '3.4'

services:
  webapptest:
    image: ${DOCKER_REGISTRY-}webapptest
    build:
      context: .
      dockerfile: WebAppTest/Dockerfile
    depends_on:
      - webapp
  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro